### ISSUE TITLE
Implement RPCh in Liquality wallet

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-bounty-submission#7]
### Job Story

Using RPCh's SDK, a wallet may send and receive RPC methods without leaking the user's data.
In this bounty, you are challenged to integrate the RPCh SDK (or one of RPCh's adaptors) into [Liquality wallet](https://github.com/liquality/wallet).

### Description

Read the [RPCh getting started guide](https://docs.rpch.net/docs/guides/get-started) and implement RPCh in [Liquality wallet](https://github.com/liquality/wallet).
A user should be able to select network named "Gnosis over RPCh" which will route all RPC requests through RPCh's SDK.

### Definition of Done

- RPCh is integrated into the wallet using RPCh SDK or one of the available RPCh adaptors
- A new network is available named "Gnosis over RPCh" which once selected, uses RPCh

### How to Apply 

- Submit a work plan in your application on Gitcoin 
- Provide an estimate of how much time you think you need to complete the bounty.

### How to submit 

- Create a pull request for our [hopr-bounty-submission repository](https://github.com/hoprnet/hopr-bounty-submission) 
- Submit your work into a new subfolder called ***implement_rpch_in_liquality_wallet***.

### What is RPCh?

Find out more about RPCh at the following links:

- [RPCh Website](https://rpch.net)
- [RPCh monorepo](https://github.com/rpc-h/rpch)
- [RPCh docs](https://docs.rpch.net)
- [discord](https://discord.com/invite/dEAWC4G)

### What is HOPR?

Find out more about HOPR at the following links:

- [HOPR Website](https://hoprnet.org)
- [hoprnet monorepo](https://github.com/hoprnet/hoprnet)
- [hoprnet docs](http://docs.hoprnet.org)
- [discord](https://discord.com/invite/7RqwJt8h)

This bounty is part of [The Bounty Program](https://bounties.hoprnet.org/)

**Comment by 0xbhagi** [comment]
Hey Martin, this is my work plan to implement RPCh in Liquality Wallet:-

I am already  familiar with RPCh SDK and  RPCh adaptors.
Integrat RPCh adaptor in Liquality Wallet.
Add a new network 'Gnosis over RPCh'  in Wallet Core lib.

Estimated time of completion: 1 week
If the Approved guy submission does not fullfill the criteria then i am on waitlist.
Thank you.

**Comment by hieple7985** [comment]
Is that available to work?

**Comment by nionis** [comment]
hey https://github.com/oguzutku1745, we have been in communication in TG, can you update here so @MartinBenediktBusch can proceed with the payout?

**Comment by oguzutku1745** [comment]
Hello @hieple7985! I had a few problems with the injection logic of the Liquality wallet. While other wallets, such as [Block Wallet](https://github.com/Rpc-h/extension-block-wallet) use a provider to utilize them, Liquality directly injects the providers (this also includes the wasm file of rpc-h) into the webpage. I did not want to change the way the Liquality Wallet works because it didn't feel safe. If you have more experience on this topic, I would be more than happy to talk and collaborate about it!

Even though the direct injection is problematic in dApps, there is no problem with the basic implementation (sending, storing & receiving funds anonymously).

Here is the Liquality Wallet with simple rpc-h implementation:
[Wallet interface](https://github.com/oguzutku1745/Privacy-wallet)
[Core Functions](https://github.com/oguzutku1745/wallet-core)

**Comment by nionis** [comment]
@oguzutku1745 IMO injecting RPCh as the provider shouldn't be an issue, it only adds additional privacy to the webpage, could you proceed with updating it so it injects RPCh's provider?

**Comment by oguzutku1745** [comment]
The main difference is that the wasm file is not being fetched in the other example integrations because they have built a communication channel between the website and the background script instead of injecting providers directly (blankProvider in blockWallet). This can be seen in the webpack configuration.

The [enKrypt](https://github.com/Rpc-h/extension-enKrypt) example is worth taking a look at. Even though they have built the background and content scripts differently, they still use a communication channel and avoid directly injecting scripts into the website.

When we inject the wasm file, abnormal behaviors such as the inability to fetch prices/tokens start to appear in dApps. That also reflects to swap actions.

The current example already injects the RPCh into the websites. To give it a try:
1- First, clone both of the files I shared above.
2- Change the paths specified in package.json according to the path of wallet-core.

There are also some minor dependency errors depending on the system that can be fixed by manually editing the yarn.lock file.

Also, note that the current version of the vue-cli is not the same as the Liquality wallet's, so I advise you to directly clone from my repo. I updated it to increase the wasm file support.
